name: Trigger auto deployment for album-ui

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/album-ui-AutoDeployTrigger-c4365ae2-7dca-468d-a8ab-43c8a99bfff8.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ALBUMUI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/src 
          registryUrl: acaalbumsyoungsamlee.azurecr.io
          registryUsername: ${{ secrets.ALBUMUI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ALBUMUI_REGISTRY_PASSWORD }}
          containerAppName: album-ui
          resourceGroup: rg-pgd-d-containers-ai
          imageToBuild: acaalbumsyoungsamlee.azurecr.io/album-ui:${{ github.sha }}
          
            

     

